name = "sor"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "DB"
class_name = "Db"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Db"]
